package App;


/**
* App/ApplicationServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Saturday, April 20, 2024 10:56:17 PM SGT
*/

public interface ApplicationServerOperations 
{
  void login (App.User user, App.Controller controller);
  void logout (App.User user);
  App.Response createLobby (App.User creator);
  App.Response joinLobby (App.User user, String lobbyId);
  App.Response leaveLobby (App.User user, String lobbyId);
  App.Lobby[] getLobby ();
} // interface ApplicationServerOperations
