package App;


/**
* App/ApplicationServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Thursday, May 9, 2024 9:41:40 AM CST
*/

public interface ApplicationServerOperations 
{
  App.User login (String userName, String password, App.Controller controller) throws App.LogInException;
  void logout (String userID);
  App.Response createAccount (App.User user) throws App.CreateException;
  App.Response createLobby (App.User creator, App.Controller clientController) throws App.LobbyException;
  App.Response joinLobby (App.User user, String lobbyId, App.Controller clientController) throws App.LobbyException;
  App.Response leaveLobby (String user, String lobbyId) throws App.LobbyException;
  App.Lobby[] getLobbies ();
  App.User[] getPlayers (String lobbyId);
  App.Response submitWord (String word, String playerId, String lobbyId);
  void startGame (String lobbyId);
  App.PlayerScore[] getPlayerScore ();
} // interface ApplicationServerOperations
