package App;


/**
* App/ApplicationServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Saturday, April 20, 2024 10:21:54 PM SGT
*/

public abstract class ApplicationServerPOA extends org.omg.PortableServer.Servant
 implements App.ApplicationServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("helloWord", new java.lang.Integer (1));
    _methods.put ("logout", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // App/ApplicationServer/login
       {
         App.User user = App.UserHelper.read (in);
         App.Controller controller = App.ControllerHelper.read (in);
         this.login (user, controller);
         out = $rh.createReply();
         break;
       }

       case 1:  // App/ApplicationServer/helloWord
       {
         String sentence = in.read_string ();
         String $result = null;
         $result = this.helloWord (sentence);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // App/ApplicationServer/logout
       {
         App.User user = App.UserHelper.read (in);
         this.logout (user);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:App/ApplicationServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ApplicationServer _this() 
  {
    return ApplicationServerHelper.narrow(
    super._this_object());
  }

  public ApplicationServer _this(org.omg.CORBA.ORB orb) 
  {
    return ApplicationServerHelper.narrow(
    super._this_object(orb));
  }


} // class ApplicationServerPOA
