package App;


/**
* App/ClientActions.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Sunday, April 21, 2024 10:38:12 AM SGT
*/

public class ClientActions implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 1;
  private static App.ClientActions[] __array = new App.ClientActions [__size];

  public static final int _NEW_MESSAGE = 0;
  public static final App.ClientActions NEW_MESSAGE = new App.ClientActions(_NEW_MESSAGE);

  public int value ()
  {
    return __value;
  }

  public static App.ClientActions from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ClientActions (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ClientActions
