package App;


/**
* App/ControllerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Saturday, April 20, 2024 10:56:17 PM SGT
*/

public interface ControllerOperations 
{
  void receiveUpdates (App.ClientActions clientActions);
  void sendUpdates (App.ClientActions clientActions);
} // interface ControllerOperations
