package App;


/**
* App/CreateException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Friday, May 10, 2024 7:58:33 PM SGT
*/

public final class CreateException extends org.omg.CORBA.UserException
{
  public String errorMessage = null;

  public CreateException ()
  {
    super(CreateExceptionHelper.id());
  } // ctor

  public CreateException (String _errorMessage)
  {
    super(CreateExceptionHelper.id());
    errorMessage = _errorMessage;
  } // ctor


  public CreateException (String $reason, String _errorMessage)
  {
    super(CreateExceptionHelper.id() + "  " + $reason);
    errorMessage = _errorMessage;
  } // ctor

} // class CreateException
