package App;

/**
* App/GamePlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Thursday, May 16, 2024 9:37:16 AM CST
*/

public final class GamePlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public App.GamePlayer value = null;

  public GamePlayerHolder ()
  {
  }

  public GamePlayerHolder (App.GamePlayer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.GamePlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.GamePlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.GamePlayerHelper.type ();
  }

}
