package App;


/**
* App/GameLobbyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, April 22, 2024 9:10:50 PM SGT
*/

public interface GameLobbyOperations 
{
  App.GameLobbyData gameData ();
  void gameData (App.GameLobbyData newGameData);
  String getId ();
} // interface GameLobbyOperations
