package App;


/**
* App/GameLobbyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, April 22, 2024 9:10:50 PM SGT
*/

abstract public class GameLobbyHelper
{
  private static String  _id = "IDL:App/GameLobby:1.0";

  public static void insert (org.omg.CORBA.Any a, App.GameLobby that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static App.GameLobby extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (App.GameLobbyHelper.id (), "GameLobby");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static App.GameLobby read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameLobbyStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, App.GameLobby value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static App.GameLobby narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof App.GameLobby)
      return (App.GameLobby)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      App._GameLobbyStub stub = new App._GameLobbyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static App.GameLobby unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof App.GameLobby)
      return (App.GameLobby)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      App._GameLobbyStub stub = new App._GameLobbyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
