package App;

/**
* App/GameLobbyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, April 22, 2024 9:10:50 PM SGT
*/

public final class GameLobbyHolder implements org.omg.CORBA.portable.Streamable
{
  public App.GameLobby value = null;

  public GameLobbyHolder ()
  {
  }

  public GameLobbyHolder (App.GameLobby initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.GameLobbyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.GameLobbyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.GameLobbyHelper.type ();
  }

}
