package App;


/**
* App/GameLobby.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, April 22, 2024 9:10:50 PM SGT
*/

public interface GameLobby extends GameLobbyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameLobby
