package App;


/**
* App/GameTimesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Thursday, May 16, 2024 10:07:05 AM CST
*/

public final class GameTimesHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public GameTimesHolder ()
  {
  }

  public GameTimesHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.GameTimesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.GameTimesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.GameTimesHelper.type ();
  }

}
