package App;

/**
* App/GameLobbyDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, April 22, 2024 9:10:50 PM SGT
*/

public final class GameLobbyDataHolder implements org.omg.CORBA.portable.Streamable
{
  public App.GameLobbyData value = null;

  public GameLobbyDataHolder ()
  {
  }

  public GameLobbyDataHolder (App.GameLobbyData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.GameLobbyDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.GameLobbyDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.GameLobbyDataHelper.type ();
  }

}
