package App;


/**
* App/GameLobbyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, April 22, 2024 9:10:50 PM SGT
*/

public abstract class GameLobbyPOA extends org.omg.PortableServer.Servant
 implements App.GameLobbyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_gameData", new java.lang.Integer (0));
    _methods.put ("_set_gameData", new java.lang.Integer (1));
    _methods.put ("getId", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // App/GameLobby/_get_gameData
       {
         App.GameLobbyData $result = null;
         $result = this.gameData ();
         out = $rh.createReply();
         App.GameLobbyDataHelper.write (out, $result);
         break;
       }

       case 1:  // App/GameLobby/_set_gameData
       {
         App.GameLobbyData newGameData = App.GameLobbyDataHelper.read (in);
         this.gameData (newGameData);
         out = $rh.createReply();
         break;
       }

       case 2:  // App/GameLobby/getId
       {
         String $result = null;
         $result = this.getId ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:App/GameLobby:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameLobby _this() 
  {
    return GameLobbyHelper.narrow(
    super._this_object());
  }

  public GameLobby _this(org.omg.CORBA.ORB orb) 
  {
    return GameLobbyHelper.narrow(
    super._this_object(orb));
  }


} // class GameLobbyPOA
