package App;


/**
* App/LobbyException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Thursday, May 9, 2024 9:41:40 AM CST
*/

public final class LobbyException extends org.omg.CORBA.UserException
{
  public String errorMessage = null;

  public LobbyException ()
  {
    super(LobbyExceptionHelper.id());
  } // ctor

  public LobbyException (String _errorMessage)
  {
    super(LobbyExceptionHelper.id());
    errorMessage = _errorMessage;
  } // ctor


  public LobbyException (String $reason, String _errorMessage)
  {
    super(LobbyExceptionHelper.id() + "  " + $reason);
    errorMessage = _errorMessage;
  } // ctor

} // class LobbyException
