package App;


/**
* App/LobbyServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, April 22, 2024 9:20:41 PM SGT
*/

public interface LobbyServerOperations 
{
  App.Response createLobby (App.User creator, App.Controller clientController);
  boolean joinLobby (App.User user, String lobbyId, App.Controller clientController);
  App.Response leaveLobby (App.User user, String lobbyId);
  App.Lobby[] getLobbies ();
} // interface LobbyServerOperations
