package App;


/**
* App/LobbyServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, May 13, 2024 9:34:31 PM SGT
*/

public interface LobbyServer extends LobbyServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LobbyServer
