package App;


/**
* App/LobbyServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Friday, May 3, 2024 3:12:17 AM SGT
*/

public interface LobbyServerOperations 
{
  App.Response createLobby (App.User creator, App.Controller clientController);
  boolean joinLobby (App.User user, String lobbyId, App.Controller clientController);
  App.Response leaveLobby (String user, String lobbyId);
  App.Lobby[] getLobbies ();
  App.Response submitWord (String word, String playerId, String lobbyId);
} // interface LobbyServerOperations
