package App;


/**
* App/LobbyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, May 13, 2024 8:52:54 PM SGT
*/

abstract public class LobbyHelper
{
  private static String  _id = "IDL:App/Lobby:1.0";

  public static void insert (org.omg.CORBA.Any a, App.Lobby that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static App.Lobby extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "lobbyId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "lobbyStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "dateCreated",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "timeCreated",
            _tcOf_members0,
            null);
          _tcOf_members0 = App.UserHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "topPlayer",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (App.LobbyHelper.id (), "Lobby", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static App.Lobby read (org.omg.CORBA.portable.InputStream istream)
  {
    App.Lobby value = new App.Lobby ();
    value.lobbyId = istream.read_string ();
    value.lobbyStatus = istream.read_string ();
    value.dateCreated = istream.read_string ();
    value.timeCreated = istream.read_string ();
    value.topPlayer = App.UserHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, App.Lobby value)
  {
    ostream.write_string (value.lobbyId);
    ostream.write_string (value.lobbyStatus);
    ostream.write_string (value.dateCreated);
    ostream.write_string (value.timeCreated);
    App.UserHelper.write (ostream, value.topPlayer);
  }

}
