package App;


/**
* App/OtherPlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Thursday, May 16, 2024 10:07:05 AM CST
*/

public final class OtherPlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public App.GamePlayer value[] = null;

  public OtherPlayersHolder ()
  {
  }

  public OtherPlayersHolder (App.GamePlayer[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.OtherPlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.OtherPlayersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.OtherPlayersHelper.type ();
  }

}
