package App;


/**
* App/PlayerScoresHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, May 6, 2024 9:20:58 AM CST
*/

public final class PlayerScoresHolder implements org.omg.CORBA.portable.Streamable
{
  public App.PlayerScore value[] = null;

  public PlayerScoresHolder ()
  {
  }

  public PlayerScoresHolder (App.PlayerScore[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.PlayerScoresHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.PlayerScoresHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.PlayerScoresHelper.type ();
  }

}
