package App;


/**
* App/PlayerScoresHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Thursday, May 9, 2024 9:41:40 AM CST
*/

abstract public class PlayerScoresHelper
{
  private static String  _id = "IDL:App/PlayerScores:1.0";

  public static void insert (org.omg.CORBA.Any a, App.PlayerScore[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static App.PlayerScore[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = App.PlayerScoreHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (App.PlayerScoresHelper.id (), "PlayerScores", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static App.PlayerScore[] read (org.omg.CORBA.portable.InputStream istream)
  {
    App.PlayerScore value[] = null;
    int _len0 = istream.read_long ();
    value = new App.PlayerScore[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = App.PlayerScoreHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, App.PlayerScore[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      App.PlayerScoreHelper.write (ostream, value[_i0]);
  }

}
