package App;

/**
* App/PlayerScoreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Thursday, May 9, 2024 9:41:40 AM CST
*/

public final class PlayerScoreHolder implements org.omg.CORBA.portable.Streamable
{
  public App.PlayerScore value = null;

  public PlayerScoreHolder ()
  {
  }

  public PlayerScoreHolder (App.PlayerScore initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.PlayerScoreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.PlayerScoreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.PlayerScoreHelper.type ();
  }

}
