package App;

/**
* App/wordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Saturday, April 20, 2024 10:56:17 PM SGT
*/

public final class wordHolder implements org.omg.CORBA.portable.Streamable
{
  public App.word value = null;

  public wordHolder ()
  {
  }

  public wordHolder (App.word initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.wordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.wordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.wordHelper.type ();
  }

}
