package App;


/**
* App/word.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Application.idl
* Monday, April 22, 2024 9:20:41 PM SGT
*/

public final class word implements org.omg.CORBA.portable.IDLEntity
{
  public int wordId = (int)0;
  public String wordName = null;

  public word ()
  {
  } // ctor

  public word (int _wordId, String _wordName)
  {
    wordId = _wordId;
    wordName = _wordName;
  } // ctor

} // class word
